# Generated by Django 5.1.4 on 2024-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_remove_file_encrypted_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="auth_tag",
            field=models.CharField(default="", max_length=24),
        ),
    ]
