# Generated by Django 5.1.4 on 2024-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_auth_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileshare",
            name="permission",
            field=models.CharField(
                choices=[
                    ("VIEW", "View"),
                    ("DOWNLOAD", "Download"),
                    ("BOTH", "View and Download"),
                ],
                default="VIEW",
                max_length=10,
            ),
        ),
    ]
